departments = """
Accounting (ACCT)
Actuarial Science (AS)
Adult & Organizational Development (AOD)
Advanced Core Medical Science (ACMS)
Advanced Education (ADVE)
Advertising (ADV)
Aerospace Studies - Air Force ROTC (AIRF)
Africology and African American Studies (AAAS)
American Studies (AMST)
Anatomy & Cell Biology (Medical School) (ANAT)
Anesthesiology (ANES)
Anthropology (ANTH)
Applied Behavior Analysis (ABA)
Arabic (ARBC)
Architecture (ARCH)
Art (ART)
Art - Japan Campus (ARTU)
Art Education (ARTE)
Art History (ARTH)
Art Therapy (ARTT)
Asian Studies (ASST)
Athletic Training (ATHT)
Basic Core Medical Science (BCMS)
Bioengineering (BIOE)
Biology (BIOL)
Biomedical Sciences (Medical) (BMSC)
Biomedical Studies (PBMS)
Botany (BOT)
Boyer College of Music & Dance (BCMD)
Business Administration (BA)
Business Education (BSED)
Career and Technical Education (CTE)
Center for the Performing and Cinematic Arts (CFA)
Chemistry (CHEM)
Chinese (CHI)
City and Regional Planning (CTRP)
Civil Engineering (CEE)
Clinical Sciences and Health Informatics (CSHI)
College of Education (COED)
College of Liberal Arts (CLA)
College of Public Health & School of Social Work (CHP)
College of Science and Technology (SCTC)
Communication and Social Influence (CSI)
Communication Management (CMGT)
Communication Sciences and Disorders (CSCD)
Communication Studies (CMST)
Communications and Theater (COMM)
Community Arts (CART)
Community Development (CDEV)
Community Health and Aging (PCHA)
Computer & Information Science (CIS)
Conflict and Communication (CNCM)
Construction Management Technology (CMT)
Counseling Psychology (CPSY)
Criminal Justice (CJ)
Critical Languages Center (CRIT)
Cultural Studies (CLST)
Dance (DANC)
Dental Public Health Sciences (DPHS)
Dermatology (DERM)
Disability Studies (DSST)
Distributive Education (DSED)
Early Childhood Education (ECED)
Earth & Environmental Science (EES)
Economics (ECON)
Education (EDUC)
Educational Administration (EDAD)
Educational Psychology (EPSY)
Electrical Engineering (ECE)
Electrical Engineering Technology (EET)
Elementary Education (ELED)
Emergency Medicine (EMMD)
Engineering (ENGR)
Engineering (General) (ENGG)
Engineering Management (EMGT)
Engineering Technology (ENGT)
English (ENG)
English Education (Elementary) (ENEE)
English Education (Secondary) (ENES)
Environmental Engineering Technology (ENVT)
Environmental Health (ENVH)
Environmental Science (CST) (ENVS)
Environmental Studies (CLA) (ENST)
Epidemiology and Biostatistics (EPBI)
Family & Community Medicine (FAMP)
Film and Media Arts (FMA)
Finance (FIN)
Foreign Language Ed-Secondary (FLED)
Foundation Program (FDPR)
French (FREN)
Gender, Sexuality and Women's Studies (GSWS)
Geography and Urban Studies (GUS)
German (GER)
Global Studies (GBST)
Globalization and Development Communication (GDC)
Graduate Advanced Education and General Dentistry (ADVG)
Graduate Endodontic (ENDG)
Graduate Orthodontics (ORTG)
Graduate Periodontics (PERG)
Graphic Arts and Design (GAD)
Greek (Ancient) (GRKA)
Greek (Modern) (GRKM)
Greek and Roman Classics (GRC)
Health Information Management (HIM)
Health Policy and Management (HPM)
Health Related Professions (HRPR)
Healthcare Management (HCM)
Hebrew (HEBR)
Higher Education (HIED)
Hindi (HIN)
History (HIST)
Honors Program (HNRS)
Horticulture (HORT)
Human Development and Community Engagement (HDCE)
Human Resource Management (HRM)
Human Services (HS)
Industrial and Systems Engineering (ISE)
Instructional Learning Technology (ILT)
Intellectual Heritage (IH)
Internal Medicine (INTM)
International Business Administration (IB)
International Teaching Assistants (ITA)
Italian (ITAL)
Japanese (JPNS)
Jewish Studies (JST)
Journalism (JRN)
Juridical Science (JUSI)
Juris Doctor (JUDO)
Kinesiology (KINS)
Klein College of Media and Communication (KLN)
Korean (KRN)
Landscape Architecture (LARC)
Latin (LAT)
Latin American Studies (LAS)
Law - Undergraduate Courses (LAWU)
Legal Studies (LGLS)
Lesbian, Gay, Bisexual and Transgender Studies (LGBT)
LLM American & International (MLAI)
LLM Freedman Fellows (MLFF)
LLM Taxation (MLTX)
LLM Trial Advocacy (MLTA)
Management Information Systems (MIS)
Management Science/Operations Management (MSOM)
Marketing (MKTG)
Master of Liberal Arts (MLA)
Math Education (Elementary) (MAEE)
Math Education (Secondary) (MAES)
Mathematics (MATH)
Mechanical Engineering (MEE)
Mechanical Engineering Technology (MET)
Media and Communication (MMC)
Media Studies & Production (MSP)
Medicine Undergraduate Courses (MEDU)
Middle Grades & Secondary Education (MGSE)
Middle Grades Education (MGRE)
Military Science (MLSC)
Music (MUSC)
Music Education (MUED)
Music Studies (MUST)
Narrative Medicine (NMED)
Naval Science - Navy ROTC (NAVS)
Neurology (NEUR)
Neuromotor Science (NMS)
Neuroscience - CLA (NSCI)
Neurosurgery (NESU)
New Media Interdisciplinary (NMIC)
Nursing (NURS)
Nutrition (NUTR)
Obstetrics, Gynecology & Reproduction (OBGY)
Occupational Therapy (OTHR)
Ophthalmology (OPHT)
Oral Biology (ORBG)
Oral Health Sciences (OHSC)
Orthopedic Surgery (ORTS)
Otorhinology (OTOR)
Pathology & Lab Medicine (PATH)
Pediatrics (PEDI)
Pharmaceutical Sciences (PS)
Pharmacy Practice (PP)
Pharmacy Quality Assurance (QARA)
Philosophy (PHIL)
Physical Therapy (PHTH)
Physician Assistant (PA)
Physics (PHYS)
Physiology-Biophysics (PHBI)
Podiatric Clinical Education (PCED)
Podiatric Interdepartmental (PDID)
Podiatric Medicine (PDMD)
Podiatric Orthopedics (PDOR)
Podiatric Surgery (PDSR)
Political Science (POLS)
Portuguese (PORT)
ProRanger Program (PRAN)
Psychiatry & Behavioral Science (PSYM)
Psychology (PSY)
Public Policy (PLCY)
Public Relations (PR)
Radiation Oncology (RAON)
Radiology (RADI)
Real Estate (RE)
Recreational Therapy (RCTH)
Rehabilitation Medicine (RHMD)
Rehabilitation Sciences (REHB)
Religion (REL)
Restorative Dentistry (RDNT)
Risk Management and Insurance (RMI)
Russian (RUS)
School of Business and Management (SBM)
School of Dentistry (DENT)
School of Medicine (MEDS)
School of Sport, Tourism & Hospitality Management (STHA)
School Psychology (SPSY)
Science Education (Elementary) (SCEE)
Science Education (Secondary) (SCES)
Science, Secondary Education (SCSE)
Secondary Education (SECE)
Slavic Languages & Literature (SLVC)
Social and Behavioral Sciences (SBS)
Social Studies Education (Elementary) (SSEE)
Social Studies Education (Secondary) (SSES)
Social Work - Graduate (SSWG)
Social Work - Undergraduate (SSWU)
Sociology (SOC)
Spanish (SPAN)
Special Education (SPED)
Sport and Recreation Management (SRM)
Sport, Tourism and Hospitality Management (STHM)
Statistics (STAT)
Strategic Communication (STRC)
Strategic Management (SGM)
Study Away Non-TU Program (STAW)
Supervisory Certification Prog (SUPV)
Supply Chain Management (SCM)
Surgery (SURG)
Teaching English to Speakers of Other Languages (TESL)
Temple University Japan (TUJ)
Theater (THTR)
Theater, Film and Media Arts (TFMA)
Therapeutic Recreation (THRC)
Topical Studies (TS)
Tourism and Hospitality Management (THM)
TUJ International Business Studies (JIBS)
Tyler School of Art (TYLE)
Undergraduate Studies Merit Scholar (USMS)
University College (UC)
University Seminar (UNVS)
Upper Division Honors Program (HONS)
Urban Bioethics (UBTH)
Urban Education (URBE)
Urology (UROL)
Visual Studies (VS)
"""

department_options = []
lines = departments.strip().split("\n")

for line in lines:
    parts = line.split(" (")
    value = parts[1].replace(")", "")
    label = parts[0]
    department_options.append({ "value": value, "label": label })

for department_options in department_options:
    print(department_options, end=",\n")